name: Main workflow

on: 
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test_run:
    runs-on: ubuntu-latest
    steps:
    # Clone the repository
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    # Set up the environment
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    # Install the requirements
    - name: Install jupyter and pytest
      run: |
        pip install jupyter pytest
    # Convert notebooks to Python code
    - name: convert ipynb to py
      run: |
        jupyter nbconvert --to python notebooks/*.ipynb --output-dir=auto_generated_scripts
    # Run the tests and check for errors
    - name: Run tests on notebooks and scripts
      run: |
        pytest
    # Commit py files (does not run on pull requests)
    - name: Commit py files
      run: |
        git config --local user.name github-actions
        git config --local user.email github-actions@github.com
        git add auto_generated_scripts/*.py
        git commit -m "auto generated py files" || echo "No changes to commit"
        git push
      if: github.event_name == 'push'  # Don't run on pull requests
    # Locally build Jupyter-book
    - name: Build the book
      run: |
        pip install -r requirements.txt
        jupyter-book build ./
    # Push the book to the gh-pages branch  (does not run on pull requests)
    - name: Push jupyter-book to gh-pages
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/html
      if: github.event_name == 'push'  # Don't run on pull requests
